// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef DATAMOVER_REGIF_H
#define DATAMOVER_REGIF_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - datamover_regif::hwpe_commit_trigger
#define DATAMOVER_REGIF__HWPE_COMMIT_TRIGGER__COMMIT_TRIGGER_bm 0x3
#define DATAMOVER_REGIF__HWPE_COMMIT_TRIGGER__COMMIT_TRIGGER_bp 0
#define DATAMOVER_REGIF__HWPE_COMMIT_TRIGGER__COMMIT_TRIGGER_bw 2
#define DATAMOVER_REGIF__HWPE_COMMIT_TRIGGER__COMMIT_TRIGGER_reset 0x0
#define DATAMOVER_REGIF__HWPE_COMMIT_TRIGGER__R0_bm 0xfffffffc
#define DATAMOVER_REGIF__HWPE_COMMIT_TRIGGER__R0_bp 2
#define DATAMOVER_REGIF__HWPE_COMMIT_TRIGGER__R0_bw 30
#define DATAMOVER_REGIF__HWPE_COMMIT_TRIGGER__R0_reset 0x0

// reg - datamover_regif::hwpe_acquire
#define DATAMOVER_REGIF__HWPE_ACQUIRE__ACQUIRE_bm 0xffffffff
#define DATAMOVER_REGIF__HWPE_ACQUIRE__ACQUIRE_bp 0
#define DATAMOVER_REGIF__HWPE_ACQUIRE__ACQUIRE_bw 32
#define DATAMOVER_REGIF__HWPE_ACQUIRE__ACQUIRE_reset 0x0

// reg - datamover_regif::hwpe_autotrigger
#define DATAMOVER_REGIF__HWPE_AUTOTRIGGER__AUTOTRIGGER_N_bm 0x1
#define DATAMOVER_REGIF__HWPE_AUTOTRIGGER__AUTOTRIGGER_N_bp 0
#define DATAMOVER_REGIF__HWPE_AUTOTRIGGER__AUTOTRIGGER_N_bw 1
#define DATAMOVER_REGIF__HWPE_AUTOTRIGGER__AUTOTRIGGER_N_reset 0x0
#define DATAMOVER_REGIF__HWPE_AUTOTRIGGER__R0_bm 0xfffffffe
#define DATAMOVER_REGIF__HWPE_AUTOTRIGGER__R0_bp 1
#define DATAMOVER_REGIF__HWPE_AUTOTRIGGER__R0_bw 31
#define DATAMOVER_REGIF__HWPE_AUTOTRIGGER__R0_reset 0x0

// reg - datamover_regif::hwpe_status
#define DATAMOVER_REGIF__HWPE_STATUS__STATUS0_bm 0xffffffff
#define DATAMOVER_REGIF__HWPE_STATUS__STATUS0_bp 0
#define DATAMOVER_REGIF__HWPE_STATUS__STATUS0_bw 32
#define DATAMOVER_REGIF__HWPE_STATUS__STATUS0_reset 0x0

// reg - datamover_regif::hwpe_running_job
#define DATAMOVER_REGIF__HWPE_RUNNING_JOB__RUNNING_JOB_bm 0xff
#define DATAMOVER_REGIF__HWPE_RUNNING_JOB__RUNNING_JOB_bp 0
#define DATAMOVER_REGIF__HWPE_RUNNING_JOB__RUNNING_JOB_bw 8
#define DATAMOVER_REGIF__HWPE_RUNNING_JOB__RUNNING_JOB_reset 0x0
#define DATAMOVER_REGIF__HWPE_RUNNING_JOB__R0_bm 0xffffff00
#define DATAMOVER_REGIF__HWPE_RUNNING_JOB__R0_bp 8
#define DATAMOVER_REGIF__HWPE_RUNNING_JOB__R0_bw 24
#define DATAMOVER_REGIF__HWPE_RUNNING_JOB__R0_reset 0x0

// reg - datamover_regif::hwpe_soft_clear
#define DATAMOVER_REGIF__HWPE_SOFT_CLEAR__SOFT_CLEAR_bm 0x3
#define DATAMOVER_REGIF__HWPE_SOFT_CLEAR__SOFT_CLEAR_bp 0
#define DATAMOVER_REGIF__HWPE_SOFT_CLEAR__SOFT_CLEAR_bw 2
#define DATAMOVER_REGIF__HWPE_SOFT_CLEAR__SOFT_CLEAR_reset 0x0
#define DATAMOVER_REGIF__HWPE_SOFT_CLEAR__R0_bm 0xfffffffc
#define DATAMOVER_REGIF__HWPE_SOFT_CLEAR__R0_bp 2
#define DATAMOVER_REGIF__HWPE_SOFT_CLEAR__R0_bw 30
#define DATAMOVER_REGIF__HWPE_SOFT_CLEAR__R0_reset 0x0

// reg - datamover_regif::hwpe_reserved
#define DATAMOVER_REGIF__HWPE_RESERVED__RESERVED_bm 0xffffffff
#define DATAMOVER_REGIF__HWPE_RESERVED__RESERVED_bp 0
#define DATAMOVER_REGIF__HWPE_RESERVED__RESERVED_bw 32
#define DATAMOVER_REGIF__HWPE_RESERVED__RESERVED_reset 0x0

// regfile - datamover_regif::hwpe_ctrl_mandatory
typedef struct {
    uint32_t commit_trigger;
    uint32_t acquire;
    uint32_t autotrigger;
    uint32_t status;
    uint32_t running_job;
    uint32_t soft_clear;
    uint32_t reserved1;
    uint32_t reserved2;
} datamover_regif__hwpe_ctrl_mandatory_t;

// regfile - datamover_regif::hwpe_ctrl_job_indep
typedef struct {
    uint32_t reserved;
} datamover_regif__hwpe_ctrl_job_indep_t;

// reg - datamover_regif::dm_value32
#define DATAMOVER_REGIF__DM_VALUE32__VALUE_bm 0xffffffff
#define DATAMOVER_REGIF__DM_VALUE32__VALUE_bp 0
#define DATAMOVER_REGIF__DM_VALUE32__VALUE_bw 32
#define DATAMOVER_REGIF__DM_VALUE32__VALUE_reset 0x0

// reg - datamover_regif::dm_stride_len
#define DATAMOVER_REGIF__DM_STRIDE_LEN__LENGTH_bm 0xffff
#define DATAMOVER_REGIF__DM_STRIDE_LEN__LENGTH_bp 0
#define DATAMOVER_REGIF__DM_STRIDE_LEN__LENGTH_bw 16
#define DATAMOVER_REGIF__DM_STRIDE_LEN__LENGTH_reset 0x0
#define DATAMOVER_REGIF__DM_STRIDE_LEN__STRIDE_bm 0xffff0000
#define DATAMOVER_REGIF__DM_STRIDE_LEN__STRIDE_bp 16
#define DATAMOVER_REGIF__DM_STRIDE_LEN__STRIDE_bw 16
#define DATAMOVER_REGIF__DM_STRIDE_LEN__STRIDE_reset 0x0

// reg - datamover_regif::dm_matrix_dim
#define DATAMOVER_REGIF__DM_MATRIX_DIM__TENSOR_SIZE_M_bm 0xffff
#define DATAMOVER_REGIF__DM_MATRIX_DIM__TENSOR_SIZE_M_bp 0
#define DATAMOVER_REGIF__DM_MATRIX_DIM__TENSOR_SIZE_M_bw 16
#define DATAMOVER_REGIF__DM_MATRIX_DIM__TENSOR_SIZE_M_reset 0x0
#define DATAMOVER_REGIF__DM_MATRIX_DIM__TENSOR_SIZE_N_bm 0xffff0000
#define DATAMOVER_REGIF__DM_MATRIX_DIM__TENSOR_SIZE_N_bp 16
#define DATAMOVER_REGIF__DM_MATRIX_DIM__TENSOR_SIZE_N_bw 16
#define DATAMOVER_REGIF__DM_MATRIX_DIM__TENSOR_SIZE_N_reset 0x0

// reg - datamover_regif::dm_channels
#define DATAMOVER_REGIF__DM_CHANNELS__NUM_CHANNELS_bm 0x7ff
#define DATAMOVER_REGIF__DM_CHANNELS__NUM_CHANNELS_bp 0
#define DATAMOVER_REGIF__DM_CHANNELS__NUM_CHANNELS_bw 11
#define DATAMOVER_REGIF__DM_CHANNELS__NUM_CHANNELS_reset 0x0
#define DATAMOVER_REGIF__DM_CHANNELS__TOTAL_ELEMENTS_bm 0xfffff800
#define DATAMOVER_REGIF__DM_CHANNELS__TOTAL_ELEMENTS_bp 11
#define DATAMOVER_REGIF__DM_CHANNELS__TOTAL_ELEMENTS_bw 21
#define DATAMOVER_REGIF__DM_CHANNELS__TOTAL_ELEMENTS_reset 0x0

// reg - datamover_regif::dm_ctrl_engine
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__TRANSP_MODE_bm 0x7
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__TRANSP_MODE_bp 0
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__TRANSP_MODE_bw 3
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__TRANSP_MODE_reset 0x0
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__DATAMOVER_MODE_bm 0xf8
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__DATAMOVER_MODE_bp 3
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__DATAMOVER_MODE_bw 5
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__DATAMOVER_MODE_reset 0x0
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__READ_DIM_EN_bm 0xf00
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__READ_DIM_EN_bp 8
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__READ_DIM_EN_bw 4
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__READ_DIM_EN_reset 0x0
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__WRITE_DIM_EN_bm 0xf000
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__WRITE_DIM_EN_bp 12
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__WRITE_DIM_EN_bw 4
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__WRITE_DIM_EN_reset 0x0
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__CONV_STRIDE_bm 0x70000
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__CONV_STRIDE_bp 16
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__CONV_STRIDE_bw 3
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__CONV_STRIDE_reset 0x0
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__IM2COL_PACK_bm 0x80000
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__IM2COL_PACK_bp 19
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__IM2COL_PACK_bw 1
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__IM2COL_PACK_reset 0x0
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__PACK_LOG2W_bm 0x700000
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__PACK_LOG2W_bp 20
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__PACK_LOG2W_bw 3
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__PACK_LOG2W_reset 0x0
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__PACK_ROW_STRIDE_bm 0x7f800000
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__PACK_ROW_STRIDE_bp 23
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__PACK_ROW_STRIDE_bw 8
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__PACK_ROW_STRIDE_reset 0x0
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__IM2COL_PAD_bm 0x80000000
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__IM2COL_PAD_bp 31
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__IM2COL_PAD_bw 1
#define DATAMOVER_REGIF__DM_CTRL_ENGINE__IM2COL_PAD_reset 0x0

// reg - datamover_regif::dm_out_tot_len
#define DATAMOVER_REGIF__DM_OUT_TOT_LEN__VALUE_bm 0xffffffff
#define DATAMOVER_REGIF__DM_OUT_TOT_LEN__VALUE_bp 0
#define DATAMOVER_REGIF__DM_OUT_TOT_LEN__VALUE_bw 32
#define DATAMOVER_REGIF__DM_OUT_TOT_LEN__VALUE_reset 0x0

// regfile - datamover_regif::hwpe_ctrl_job_dep
typedef struct {
    uint32_t in_ptr;
    uint32_t out_ptr;
    uint32_t tot_len;
    uint32_t in_d0;
    uint32_t in_d1;
    uint32_t in_d2;
    uint32_t in_d3;
    uint32_t out_d0;
    uint32_t out_d1;
    uint32_t out_d2;
    uint32_t out_d3;
    uint32_t in_d4_stride;
    uint32_t out_d4_stride;
    uint32_t matrix_dim;
    uint32_t channels;
    uint32_t ctrl_engine;
    uint32_t out_tot_len;
} datamover_regif__hwpe_ctrl_job_dep_t;

// addrmap - datamover_regif
typedef struct {
    datamover_regif__hwpe_ctrl_mandatory_t hwpe_ctrl;
    datamover_regif__hwpe_ctrl_job_indep_t hwpe_job_indep;
    uint8_t RESERVED_24_3f[0x1c];
    datamover_regif__hwpe_ctrl_job_dep_t hwpe_job_dep;
} datamover_regif_t;


static_assert(sizeof(datamover_regif_t) == 0x84, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* DATAMOVER_REGIF_H */
