variables:
  GIT_SUBMODULE_STRATEGY: none
  PARALLEL: "4"
  TIMEOUT: "300"
  VSIM_FLAGS: "-c"
  # Skip debug_logs creation for CI
  NO_DEBUG: "1"
  UV_CACHE_DIR: $CI_BUILDS_DIR/../cache/uv

before_script:
  - unset VIRTUAL_ENV
  - export UV_LINK_MODE=hardlink
  - uv sync --frozen --python 3.11
  - source .venv/bin/activate
  - bender checkout

stages:
  - test

.test-template:
  stage: test
  script:
    - make run-test TEST_JSON=${TEST_JSON} PARALLEL=${PARALLEL} TIMEOUT=${TIMEOUT} NO_DEBUG=${NO_DEBUG} VSIM_FLAGS=${VSIM_FLAGS}
  artifacts:
    when: always
    expire_in: 1 year
    paths:
      - reports/
    reports:
      junit: reports/junit/${SUITE_NAME}.xml

test:transpose:
  extends: .test-template
  variables:
    TEST_JSON: utils/datamover_transpose_tests.json
    SUITE_NAME: datamover_transpose_tests

test:copy:
  extends: .test-template
  variables:
    TEST_JSON: utils/datamover_copy_tests.json
    SUITE_NAME: datamover_copy_tests

test:cim:
  extends: .test-template
  variables:
    TEST_JSON: utils/datamover_cim_tests.json
    SUITE_NAME: datamover_cim_tests

test:konark_ci:
  extends: .test-template
  variables:
    TEST_JSON: utils/datamover_konark_ci_tests.json
    SUITE_NAME: datamover_konark_ci_tests
