# Copyright 2025-2026 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Authors: Lionnus Kesting <lkesting@iis.ee.ethz.ch>

"""Emit the C headers consumed by the RTL testbench.

- `emit_task_artifacts` writes task<i>_data.h (golden_in/golden_out arrays) and
  returns metadata consumed by `write_workload_header`.
- `write_workload_header` writes the top-level datamover_workload.h.
- `write_test_config_mk` writes RTL compile-time params for the Makefile.
"""

import os

import numpy as np

from datamover_model.headers.writers import hex_byte_lines, write_define_header

HW_KEYS = ("BANDWIDTH", "WORD_WIDTH", "ELEM_WIDTH", "MISALIGNED_ACCESSES")
PARAM_KEYS = (
    "DATAMOVER_MODE",
    "TRANSP_MODE",
    "CIM_MODE",
    "ROW_TILE_SIZE",
    "SIZE_C",
    "SIZE_M",
    "SIZE_N",
    "COUNT",
    "KERNEL_SIZE",
    "CONV_STRIDE",
    "CONV_PAD",
)


def emit_task_artifacts(result, output_dir: str, index: int, in_from=None, verify: bool = True) -> dict:
    """Write task<index>_data.h; return metadata for the workload header.

    in_from: None for a standalone task / the first chain stage (its input comes
    from task<index>_golden_in); otherwise the index of the task whose output
    buffer feeds this task's input (chain wiring).
    verify: True to emit a golden_out array and check this task's output.
    """
    out_size = int(np.prod(result.out_tensor.shape))
    guard = f"TASK{index}_DATA_H"
    path = os.path.join(output_dir, f"task{index}_data.h")

    lines = [f"#ifndef {guard}", f"#define {guard}", "", "#include <stdint.h>", "",
             f"#define TASK{index}_OUT_SIZE {out_size}", ""]
    if in_from is None:
        in_size = int(np.prod(result.in_tensor.shape))
        lines += [f"#define TASK{index}_IN_SIZE  {in_size}", "",
                  f"uint8_t task{index}_golden_in[{in_size}] __attribute__((aligned(8))) = {{"]
        lines += hex_byte_lines(result.in_tensor)
        lines += ["};", ""]
    if verify:
        lines += [f"uint8_t task{index}_golden_out[{out_size}] __attribute__((aligned(8))) = {{"]
        lines += hex_byte_lines(result.out_tensor)
        lines += ["};", ""]
    lines += [f"#endif /* {guard} */", ""]

    with open(path, "w") as f:
        f.write("\n".join(lines))

    return {
        "index": index, "name": result.name, "params": result.params, "out_size": out_size,
        "verify": 1 if verify else 0,
        "in_ptr": f"task{in_from}_out" if in_from is not None else f"task{index}_golden_in",
        "out_golden": f"task{index}_golden_out" if verify else f"task{index}_out",
    }


def write_workload_header(tasks_metadata: list, hw: dict, output_dir: str) -> str:
    """Emit datamover_workload.h: HW/per-task #defines + DATAMOVER_TASKS expander."""
    num_tasks = len(tasks_metadata)
    includes = [f"task{m['index']}_data.h" for m in tasks_metadata]

    defines = [("NUM_TASKS", num_tasks)]
    for k in HW_KEYS:
        defines.append((f"DM_HW_{k}", hw[k]))
    for m in tasks_metadata:
        i = m["index"]
        for k in PARAM_KEYS:
            defines.append((f"TASK{i}_{k}", m["params"][k]))
        defines.append((f"TASK{i}_TOT_SIZE", f"(TASK{i}_SIZE_C * TASK{i}_SIZE_M * TASK{i}_SIZE_N)"))
        defines.append((f"TASK{i}_IN_PTR", m.get("in_ptr", f"task{i}_golden_in")))
        defines.append((f"TASK{i}_OUT_GOLDEN", m.get("out_golden", f"task{i}_golden_out")))
        defines.append((f"TASK{i}_VERIFY", m.get("verify", 1)))
        defines.append((f"TASK{i}_NAME", f"\"{m['name']}\""))

    macro = ["#define DATAMOVER_TASKS(APPLY) \\"]
    for i in range(num_tasks):
        macro.append(f"    APPLY({i})" + (" \\" if i < num_tasks - 1 else ""))

    path = os.path.join(output_dir, "datamover_workload.h")
    return write_define_header(path, includes, defines, macro)


def write_test_config_mk(hw: dict, output_dir: str) -> str:
    """Write test_config.mk with RTL compile-time params for the DUT."""
    path = os.path.join(output_dir, "test_config.mk")
    lines = [
        "# Auto-generated by datamover_model.workloads.cli - DO NOT EDIT",
        "# Included by the Makefile to set RTL compile-time params for the DUT.",
    ]
    for k in HW_KEYS:
        lines.append(f"{k} := {hw[k]}")
    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    return path
