// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package datamover_regif_pkg;

    localparam DATAMOVER_REGIF_DATA_WIDTH = 32;
    localparam DATAMOVER_REGIF_MIN_ADDR_WIDTH = 32;
    localparam DATAMOVER_REGIF_SIZE = 'h94;

    typedef struct packed {
        logic [31:0] next;
    } datamover_regif__hwpe_acquire__acquire__in_t;

    typedef struct packed {
        datamover_regif__hwpe_acquire__acquire__in_t acquire;
    } datamover_regif__hwpe_acquire__in_t;

    typedef struct packed {
        logic [31:0] next;
    } datamover_regif__hwpe_status__status0__in_t;

    typedef struct packed {
        datamover_regif__hwpe_status__status0__in_t status0;
    } datamover_regif__hwpe_status__in_t;

    typedef struct packed {
        logic [7:0] next;
    } datamover_regif__hwpe_running_job__running_job__in_t;

    typedef struct packed {
        datamover_regif__hwpe_running_job__running_job__in_t running_job;
    } datamover_regif__hwpe_running_job__in_t;

    typedef struct packed {
        datamover_regif__hwpe_acquire__in_t acquire;
        datamover_regif__hwpe_status__in_t status;
        datamover_regif__hwpe_running_job__in_t running_job;
    } datamover_regif__hwpe_ctrl_mandatory__in_t;

    typedef struct packed {
        datamover_regif__hwpe_ctrl_mandatory__in_t hwpe_ctrl;
    } datamover_regif__in_t;

    typedef struct packed {
        logic [1:0] value;
        logic swacc;
    } datamover_regif__hwpe_commit_trigger__commit_trigger__out_t;

    typedef struct packed {
        logic [29:0] value;
    } datamover_regif__hwpe_commit_trigger__r0__out_t;

    typedef struct packed {
        datamover_regif__hwpe_commit_trigger__commit_trigger__out_t commit_trigger;
        datamover_regif__hwpe_commit_trigger__r0__out_t r0;
    } datamover_regif__hwpe_commit_trigger__out_t;

    typedef struct packed {
        logic swacc;
    } datamover_regif__hwpe_acquire__acquire__out_t;

    typedef struct packed {
        datamover_regif__hwpe_acquire__acquire__out_t acquire;
    } datamover_regif__hwpe_acquire__out_t;

    typedef struct packed {
        logic value;
    } datamover_regif__hwpe_autotrigger__autotrigger_n__out_t;

    typedef struct packed {
        logic [30:0] value;
    } datamover_regif__hwpe_autotrigger__r0__out_t;

    typedef struct packed {
        datamover_regif__hwpe_autotrigger__autotrigger_n__out_t autotrigger_n;
        datamover_regif__hwpe_autotrigger__r0__out_t r0;
    } datamover_regif__hwpe_autotrigger__out_t;

    typedef struct packed {
        logic [23:0] value;
    } datamover_regif__hwpe_running_job__r0__out_t;

    typedef struct packed {
        datamover_regif__hwpe_running_job__r0__out_t r0;
    } datamover_regif__hwpe_running_job__out_t;

    typedef struct packed {
        logic [1:0] value;
        logic swacc;
    } datamover_regif__hwpe_soft_clear__soft_clear__out_t;

    typedef struct packed {
        logic [29:0] value;
    } datamover_regif__hwpe_soft_clear__r0__out_t;

    typedef struct packed {
        datamover_regif__hwpe_soft_clear__soft_clear__out_t soft_clear;
        datamover_regif__hwpe_soft_clear__r0__out_t r0;
    } datamover_regif__hwpe_soft_clear__out_t;

    typedef struct packed {
        logic [31:0] value;
    } datamover_regif__hwpe_reserved__reserved__out_t;

    typedef struct packed {
        datamover_regif__hwpe_reserved__reserved__out_t reserved;
    } datamover_regif__hwpe_reserved__out_t;

    typedef struct packed {
        datamover_regif__hwpe_commit_trigger__out_t commit_trigger;
        datamover_regif__hwpe_acquire__out_t acquire;
        datamover_regif__hwpe_autotrigger__out_t autotrigger;
        datamover_regif__hwpe_running_job__out_t running_job;
        datamover_regif__hwpe_soft_clear__out_t soft_clear;
        datamover_regif__hwpe_reserved__out_t reserved1;
        datamover_regif__hwpe_reserved__out_t reserved2;
    } datamover_regif__hwpe_ctrl_mandatory__out_t;

    typedef struct packed {
        datamover_regif__hwpe_reserved__out_t reserved;
    } datamover_regif__hwpe_ctrl_job_indep__out_t;

    typedef struct packed {
        logic [31:0] value;
    } datamover_regif__dm_value32__value__out_t;

    typedef struct packed {
        datamover_regif__dm_value32__value__out_t value;
    } datamover_regif__dm_value32__out_t;

    typedef struct packed {
        logic [31:0] value;
    } datamover_regif__dm_out_tot_len__value__out_t;

    typedef struct packed {
        datamover_regif__dm_out_tot_len__value__out_t value;
    } datamover_regif__dm_out_tot_len__out_t;

    typedef struct packed {
        logic [20:0] value;
    } datamover_regif__dm_stride__stride__out_t;

    typedef struct packed {
        datamover_regif__dm_stride__stride__out_t stride;
    } datamover_regif__dm_stride__out_t;

    typedef struct packed {
        logic [15:0] value;
    } datamover_regif__dm_len_d0_d1__d0__out_t;

    typedef struct packed {
        logic [15:0] value;
    } datamover_regif__dm_len_d0_d1__d1__out_t;

    typedef struct packed {
        datamover_regif__dm_len_d0_d1__d0__out_t d0;
        datamover_regif__dm_len_d0_d1__d1__out_t d1;
    } datamover_regif__dm_len_d0_d1__out_t;

    typedef struct packed {
        logic [15:0] value;
    } datamover_regif__dm_len_d2_d3__d2__out_t;

    typedef struct packed {
        logic [15:0] value;
    } datamover_regif__dm_len_d2_d3__d3__out_t;

    typedef struct packed {
        datamover_regif__dm_len_d2_d3__d2__out_t d2;
        datamover_regif__dm_len_d2_d3__d3__out_t d3;
    } datamover_regif__dm_len_d2_d3__out_t;

    typedef struct packed {
        logic [15:0] value;
    } datamover_regif__dm_matrix_dim__tensor_size_m__out_t;

    typedef struct packed {
        logic [15:0] value;
    } datamover_regif__dm_matrix_dim__tensor_size_n__out_t;

    typedef struct packed {
        datamover_regif__dm_matrix_dim__tensor_size_m__out_t tensor_size_m;
        datamover_regif__dm_matrix_dim__tensor_size_n__out_t tensor_size_n;
    } datamover_regif__dm_matrix_dim__out_t;

    typedef struct packed {
        logic [10:0] value;
    } datamover_regif__dm_channels__num_channels__out_t;

    typedef struct packed {
        logic [20:0] value;
    } datamover_regif__dm_channels__total_elements__out_t;

    typedef struct packed {
        datamover_regif__dm_channels__num_channels__out_t num_channels;
        datamover_regif__dm_channels__total_elements__out_t total_elements;
    } datamover_regif__dm_channels__out_t;

    typedef struct packed {
        logic [2:0] value;
    } datamover_regif__dm_ctrl_engine__transp_mode__out_t;

    typedef struct packed {
        logic [4:0] value;
    } datamover_regif__dm_ctrl_engine__datamover_mode__out_t;

    typedef struct packed {
        logic [3:0] value;
    } datamover_regif__dm_ctrl_engine__read_dim_en__out_t;

    typedef struct packed {
        logic [3:0] value;
    } datamover_regif__dm_ctrl_engine__write_dim_en__out_t;

    typedef struct packed {
        logic [2:0] value;
    } datamover_regif__dm_ctrl_engine__conv_stride__out_t;

    typedef struct packed {
        logic value;
    } datamover_regif__dm_ctrl_engine__im2col_pack__out_t;

    typedef struct packed {
        logic [2:0] value;
    } datamover_regif__dm_ctrl_engine__im2col_log2w__out_t;

    typedef struct packed {
        datamover_regif__dm_ctrl_engine__transp_mode__out_t transp_mode;
        datamover_regif__dm_ctrl_engine__datamover_mode__out_t datamover_mode;
        datamover_regif__dm_ctrl_engine__read_dim_en__out_t read_dim_en;
        datamover_regif__dm_ctrl_engine__write_dim_en__out_t write_dim_en;
        datamover_regif__dm_ctrl_engine__conv_stride__out_t conv_stride;
        datamover_regif__dm_ctrl_engine__im2col_pack__out_t im2col_pack;
        datamover_regif__dm_ctrl_engine__im2col_log2w__out_t im2col_log2w;
    } datamover_regif__dm_ctrl_engine__out_t;

    typedef struct packed {
        datamover_regif__dm_value32__out_t in_ptr;
        datamover_regif__dm_value32__out_t out_ptr;
        datamover_regif__dm_value32__out_t tot_len;
        datamover_regif__dm_out_tot_len__out_t out_tot_len;
        datamover_regif__dm_stride__out_t in_stride0;
        datamover_regif__dm_stride__out_t in_stride1;
        datamover_regif__dm_stride__out_t in_stride2;
        datamover_regif__dm_stride__out_t in_stride3;
        datamover_regif__dm_stride__out_t in_stride4;
        datamover_regif__dm_len_d0_d1__out_t in_len_d0_d1;
        datamover_regif__dm_len_d2_d3__out_t in_len_d2_d3;
        datamover_regif__dm_stride__out_t out_stride0;
        datamover_regif__dm_stride__out_t out_stride1;
        datamover_regif__dm_stride__out_t out_stride2;
        datamover_regif__dm_stride__out_t out_stride3;
        datamover_regif__dm_stride__out_t out_stride4;
        datamover_regif__dm_len_d0_d1__out_t out_len_d0_d1;
        datamover_regif__dm_len_d2_d3__out_t out_len_d2_d3;
        datamover_regif__dm_matrix_dim__out_t matrix_dim;
        datamover_regif__dm_channels__out_t channels;
        datamover_regif__dm_ctrl_engine__out_t ctrl_engine;
    } datamover_regif__hwpe_ctrl_job_dep__out_t;

    typedef struct packed {
        datamover_regif__hwpe_ctrl_mandatory__out_t hwpe_ctrl;
        datamover_regif__hwpe_ctrl_job_indep__out_t hwpe_job_indep;
        datamover_regif__hwpe_ctrl_job_dep__out_t hwpe_job_dep;
    } datamover_regif__out_t;
endpackage
