// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module datamover_regif (
        input wire clk,
        input wire arst_n,

        input wire s_cpuif_req,
        input wire s_cpuif_req_is_wr,
        input wire [31:0] s_cpuif_addr,
        input wire [31:0] s_cpuif_wr_data,
        input wire [31:0] s_cpuif_wr_biten,
        output wire s_cpuif_req_stall_wr,
        output wire s_cpuif_req_stall_rd,
        output wire s_cpuif_rd_ack,
        output wire s_cpuif_rd_err,
        output wire [31:0] s_cpuif_rd_data,
        output wire s_cpuif_wr_ack,
        output wire s_cpuif_wr_err,

        input datamover_regif_pkg::datamover_regif__in_t hwif_in,
        output datamover_regif_pkg::datamover_regif__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [31:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    assign cpuif_req = s_cpuif_req;
    assign cpuif_req_is_wr = s_cpuif_req_is_wr;
    assign cpuif_addr = s_cpuif_addr;
    assign cpuif_wr_data = s_cpuif_wr_data;
    assign cpuif_wr_biten = s_cpuif_wr_biten;
    assign s_cpuif_req_stall_wr = cpuif_req_stall_wr;
    assign s_cpuif_req_stall_rd = cpuif_req_stall_rd;
    assign s_cpuif_rd_ack = cpuif_rd_ack;
    assign s_cpuif_rd_err = cpuif_rd_err;
    assign s_cpuif_rd_data = cpuif_rd_data;
    assign s_cpuif_wr_ack = cpuif_wr_ack;
    assign s_cpuif_wr_err = cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            logic commit_trigger;
            logic acquire;
            logic autotrigger;
            logic status;
            logic running_job;
            logic soft_clear;
            logic reserved1;
            logic reserved2;
        } hwpe_ctrl;
        struct {
            logic reserved;
        } hwpe_job_indep;
        struct {
            logic in_ptr;
            logic out_ptr;
            logic tot_len;
            logic in_d0;
            logic in_d1;
            logic in_d2;
            logic in_d3;
            logic out_d0;
            logic out_d1;
            logic out_d2;
            logic out_d3;
            logic in_out_d4_stride;
            logic matrix_dim;
            logic channels;
            logic ctrl_engine;
            logic out_tot_len;
        } hwpe_job_dep;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [31:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.hwpe_ctrl.commit_trigger = cpuif_req_masked & (cpuif_addr == 32'h0);
        decoded_reg_strb.hwpe_ctrl.acquire = cpuif_req_masked & (cpuif_addr == 32'h4) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_ctrl.autotrigger = cpuif_req_masked & (cpuif_addr == 32'h8);
        decoded_reg_strb.hwpe_ctrl.status = cpuif_req_masked & (cpuif_addr == 32'hc) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_ctrl.running_job = cpuif_req_masked & (cpuif_addr == 32'h10) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_ctrl.soft_clear = cpuif_req_masked & (cpuif_addr == 32'h14);
        decoded_reg_strb.hwpe_ctrl.reserved1 = cpuif_req_masked & (cpuif_addr == 32'h18) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_ctrl.reserved2 = cpuif_req_masked & (cpuif_addr == 32'h1c) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_job_indep.reserved = cpuif_req_masked & (cpuif_addr == 32'h20) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_job_dep.in_ptr = cpuif_req_masked & (cpuif_addr == 32'h40);
        decoded_reg_strb.hwpe_job_dep.out_ptr = cpuif_req_masked & (cpuif_addr == 32'h44);
        decoded_reg_strb.hwpe_job_dep.tot_len = cpuif_req_masked & (cpuif_addr == 32'h48);
        decoded_reg_strb.hwpe_job_dep.in_d0 = cpuif_req_masked & (cpuif_addr == 32'h4c);
        decoded_reg_strb.hwpe_job_dep.in_d1 = cpuif_req_masked & (cpuif_addr == 32'h50);
        decoded_reg_strb.hwpe_job_dep.in_d2 = cpuif_req_masked & (cpuif_addr == 32'h54);
        decoded_reg_strb.hwpe_job_dep.in_d3 = cpuif_req_masked & (cpuif_addr == 32'h58);
        decoded_reg_strb.hwpe_job_dep.out_d0 = cpuif_req_masked & (cpuif_addr == 32'h5c);
        decoded_reg_strb.hwpe_job_dep.out_d1 = cpuif_req_masked & (cpuif_addr == 32'h60);
        decoded_reg_strb.hwpe_job_dep.out_d2 = cpuif_req_masked & (cpuif_addr == 32'h64);
        decoded_reg_strb.hwpe_job_dep.out_d3 = cpuif_req_masked & (cpuif_addr == 32'h68);
        decoded_reg_strb.hwpe_job_dep.in_out_d4_stride = cpuif_req_masked & (cpuif_addr == 32'h6c);
        decoded_reg_strb.hwpe_job_dep.matrix_dim = cpuif_req_masked & (cpuif_addr == 32'h70);
        decoded_reg_strb.hwpe_job_dep.channels = cpuif_req_masked & (cpuif_addr == 32'h74);
        decoded_reg_strb.hwpe_job_dep.ctrl_engine = cpuif_req_masked & (cpuif_addr == 32'h78);
        decoded_reg_strb.hwpe_job_dep.out_tot_len = cpuif_req_masked & (cpuif_addr == 32'h7c);
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                struct {
                    logic [1:0] next;
                    logic load_next;
                } commit_trigger;
            } commit_trigger;
            struct {
                struct {
                    logic next;
                    logic load_next;
                } autotrigger_n;
            } autotrigger;
            struct {
                struct {
                    logic [1:0] next;
                    logic load_next;
                } soft_clear;
            } soft_clear;
        } hwpe_ctrl;
        struct {
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } in_ptr;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } out_ptr;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } tot_len;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } length;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } stride;
            } in_d0;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } length;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } stride;
            } in_d1;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } length;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } stride;
            } in_d2;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } length;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } stride;
            } in_d3;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } length;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } stride;
            } out_d0;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } length;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } stride;
            } out_d1;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } length;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } stride;
            } out_d2;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } length;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } stride;
            } out_d3;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } in_stride;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } out_stride;
            } in_out_d4_stride;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } tensor_size_m;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } tensor_size_n;
            } matrix_dim;
            struct {
                struct {
                    logic [10:0] next;
                    logic load_next;
                } num_channels;
                struct {
                    logic [20:0] next;
                    logic load_next;
                } total_elements;
            } channels;
            struct {
                struct {
                    logic [2:0] next;
                    logic load_next;
                } transp_mode;
                struct {
                    logic [4:0] next;
                    logic load_next;
                } datamover_mode;
                struct {
                    logic [3:0] next;
                    logic load_next;
                } read_dim_en;
                struct {
                    logic [3:0] next;
                    logic load_next;
                } write_dim_en;
                struct {
                    logic [2:0] next;
                    logic load_next;
                } conv_stride;
                struct {
                    logic [12:0] next;
                    logic load_next;
                } reserved;
            } ctrl_engine;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } out_tot_len;
        } hwpe_job_dep;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                struct {
                    logic [1:0] value;
                } commit_trigger;
            } commit_trigger;
            struct {
                struct {
                    logic value;
                } autotrigger_n;
            } autotrigger;
            struct {
                struct {
                    logic [1:0] value;
                } soft_clear;
            } soft_clear;
        } hwpe_ctrl;
        struct {
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } in_ptr;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } out_ptr;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } tot_len;
            struct {
                struct {
                    logic [15:0] value;
                } length;
                struct {
                    logic [15:0] value;
                } stride;
            } in_d0;
            struct {
                struct {
                    logic [15:0] value;
                } length;
                struct {
                    logic [15:0] value;
                } stride;
            } in_d1;
            struct {
                struct {
                    logic [15:0] value;
                } length;
                struct {
                    logic [15:0] value;
                } stride;
            } in_d2;
            struct {
                struct {
                    logic [15:0] value;
                } length;
                struct {
                    logic [15:0] value;
                } stride;
            } in_d3;
            struct {
                struct {
                    logic [15:0] value;
                } length;
                struct {
                    logic [15:0] value;
                } stride;
            } out_d0;
            struct {
                struct {
                    logic [15:0] value;
                } length;
                struct {
                    logic [15:0] value;
                } stride;
            } out_d1;
            struct {
                struct {
                    logic [15:0] value;
                } length;
                struct {
                    logic [15:0] value;
                } stride;
            } out_d2;
            struct {
                struct {
                    logic [15:0] value;
                } length;
                struct {
                    logic [15:0] value;
                } stride;
            } out_d3;
            struct {
                struct {
                    logic [15:0] value;
                } in_stride;
                struct {
                    logic [15:0] value;
                } out_stride;
            } in_out_d4_stride;
            struct {
                struct {
                    logic [15:0] value;
                } tensor_size_m;
                struct {
                    logic [15:0] value;
                } tensor_size_n;
            } matrix_dim;
            struct {
                struct {
                    logic [10:0] value;
                } num_channels;
                struct {
                    logic [20:0] value;
                } total_elements;
            } channels;
            struct {
                struct {
                    logic [2:0] value;
                } transp_mode;
                struct {
                    logic [4:0] value;
                } datamover_mode;
                struct {
                    logic [3:0] value;
                } read_dim_en;
                struct {
                    logic [3:0] value;
                } write_dim_en;
                struct {
                    logic [2:0] value;
                } conv_stride;
                struct {
                    logic [12:0] value;
                } reserved;
            } ctrl_engine;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } out_tot_len;
        } hwpe_job_dep;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: datamover_regif.hwpe_ctrl.commit_trigger.commit_trigger
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_ctrl.commit_trigger && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_ctrl.commit_trigger.commit_trigger.next = next_c;
        field_combo.hwpe_ctrl.commit_trigger.commit_trigger.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value <= 2'h0;
        end else begin
            if(field_combo.hwpe_ctrl.commit_trigger.commit_trigger.load_next) begin
                field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value <= field_combo.hwpe_ctrl.commit_trigger.commit_trigger.next;
            end
        end
    end
    assign hwif_out.hwpe_ctrl.commit_trigger.commit_trigger.value = field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value;
    assign hwif_out.hwpe_ctrl.commit_trigger.commit_trigger.swacc = decoded_reg_strb.hwpe_ctrl.commit_trigger;
    assign hwif_out.hwpe_ctrl.commit_trigger.r0.value = 30'h0;
    assign hwif_out.hwpe_ctrl.acquire.acquire.swacc = decoded_reg_strb.hwpe_ctrl.acquire;
    // Field: datamover_regif.hwpe_ctrl.autotrigger.autotrigger_n
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_ctrl.autotrigger.autotrigger_n.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_ctrl.autotrigger && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_ctrl.autotrigger.autotrigger_n.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_ctrl.autotrigger.autotrigger_n.next = next_c;
        field_combo.hwpe_ctrl.autotrigger.autotrigger_n.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_ctrl.autotrigger.autotrigger_n.value <= 1'h0;
        end else begin
            if(field_combo.hwpe_ctrl.autotrigger.autotrigger_n.load_next) begin
                field_storage.hwpe_ctrl.autotrigger.autotrigger_n.value <= field_combo.hwpe_ctrl.autotrigger.autotrigger_n.next;
            end
        end
    end
    assign hwif_out.hwpe_ctrl.autotrigger.autotrigger_n.value = field_storage.hwpe_ctrl.autotrigger.autotrigger_n.value;
    assign hwif_out.hwpe_ctrl.autotrigger.r0.value = 31'h0;
    assign hwif_out.hwpe_ctrl.running_job.r0.value = 24'h0;
    // Field: datamover_regif.hwpe_ctrl.soft_clear.soft_clear
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_ctrl.soft_clear.soft_clear.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_ctrl.soft_clear && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_ctrl.soft_clear.soft_clear.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_ctrl.soft_clear.soft_clear.next = next_c;
        field_combo.hwpe_ctrl.soft_clear.soft_clear.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_ctrl.soft_clear.soft_clear.value <= 2'h0;
        end else begin
            if(field_combo.hwpe_ctrl.soft_clear.soft_clear.load_next) begin
                field_storage.hwpe_ctrl.soft_clear.soft_clear.value <= field_combo.hwpe_ctrl.soft_clear.soft_clear.next;
            end
        end
    end
    assign hwif_out.hwpe_ctrl.soft_clear.soft_clear.value = field_storage.hwpe_ctrl.soft_clear.soft_clear.value;
    assign hwif_out.hwpe_ctrl.soft_clear.soft_clear.swacc = decoded_reg_strb.hwpe_ctrl.soft_clear;
    assign hwif_out.hwpe_ctrl.soft_clear.r0.value = 30'h0;
    assign hwif_out.hwpe_ctrl.reserved1.reserved.value = 32'h0;
    assign hwif_out.hwpe_ctrl.reserved2.reserved.value = 32'h0;
    assign hwif_out.hwpe_job_indep.reserved.reserved.value = 32'h0;
    // Field: datamover_regif.hwpe_job_dep.in_ptr.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.in_ptr.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.in_ptr && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.in_ptr.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.in_ptr.value.next = next_c;
        field_combo.hwpe_job_dep.in_ptr.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.in_ptr.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.in_ptr.value.load_next) begin
                field_storage.hwpe_job_dep.in_ptr.value.value <= field_combo.hwpe_job_dep.in_ptr.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.in_ptr.value.value = field_storage.hwpe_job_dep.in_ptr.value.value;
    // Field: datamover_regif.hwpe_job_dep.out_ptr.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.out_ptr.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.out_ptr && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.out_ptr.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.out_ptr.value.next = next_c;
        field_combo.hwpe_job_dep.out_ptr.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.out_ptr.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.out_ptr.value.load_next) begin
                field_storage.hwpe_job_dep.out_ptr.value.value <= field_combo.hwpe_job_dep.out_ptr.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.out_ptr.value.value = field_storage.hwpe_job_dep.out_ptr.value.value;
    // Field: datamover_regif.hwpe_job_dep.tot_len.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.tot_len.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.tot_len && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.tot_len.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.tot_len.value.next = next_c;
        field_combo.hwpe_job_dep.tot_len.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.tot_len.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.tot_len.value.load_next) begin
                field_storage.hwpe_job_dep.tot_len.value.value <= field_combo.hwpe_job_dep.tot_len.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.tot_len.value.value = field_storage.hwpe_job_dep.tot_len.value.value;
    // Field: datamover_regif.hwpe_job_dep.in_d0.length
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.in_d0.length.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.in_d0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.in_d0.length.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.in_d0.length.next = next_c;
        field_combo.hwpe_job_dep.in_d0.length.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.in_d0.length.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.in_d0.length.load_next) begin
                field_storage.hwpe_job_dep.in_d0.length.value <= field_combo.hwpe_job_dep.in_d0.length.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.in_d0.length.value = field_storage.hwpe_job_dep.in_d0.length.value;
    // Field: datamover_regif.hwpe_job_dep.in_d0.stride
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.in_d0.stride.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.in_d0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.in_d0.stride.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.in_d0.stride.next = next_c;
        field_combo.hwpe_job_dep.in_d0.stride.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.in_d0.stride.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.in_d0.stride.load_next) begin
                field_storage.hwpe_job_dep.in_d0.stride.value <= field_combo.hwpe_job_dep.in_d0.stride.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.in_d0.stride.value = field_storage.hwpe_job_dep.in_d0.stride.value;
    // Field: datamover_regif.hwpe_job_dep.in_d1.length
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.in_d1.length.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.in_d1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.in_d1.length.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.in_d1.length.next = next_c;
        field_combo.hwpe_job_dep.in_d1.length.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.in_d1.length.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.in_d1.length.load_next) begin
                field_storage.hwpe_job_dep.in_d1.length.value <= field_combo.hwpe_job_dep.in_d1.length.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.in_d1.length.value = field_storage.hwpe_job_dep.in_d1.length.value;
    // Field: datamover_regif.hwpe_job_dep.in_d1.stride
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.in_d1.stride.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.in_d1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.in_d1.stride.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.in_d1.stride.next = next_c;
        field_combo.hwpe_job_dep.in_d1.stride.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.in_d1.stride.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.in_d1.stride.load_next) begin
                field_storage.hwpe_job_dep.in_d1.stride.value <= field_combo.hwpe_job_dep.in_d1.stride.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.in_d1.stride.value = field_storage.hwpe_job_dep.in_d1.stride.value;
    // Field: datamover_regif.hwpe_job_dep.in_d2.length
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.in_d2.length.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.in_d2 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.in_d2.length.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.in_d2.length.next = next_c;
        field_combo.hwpe_job_dep.in_d2.length.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.in_d2.length.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.in_d2.length.load_next) begin
                field_storage.hwpe_job_dep.in_d2.length.value <= field_combo.hwpe_job_dep.in_d2.length.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.in_d2.length.value = field_storage.hwpe_job_dep.in_d2.length.value;
    // Field: datamover_regif.hwpe_job_dep.in_d2.stride
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.in_d2.stride.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.in_d2 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.in_d2.stride.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.in_d2.stride.next = next_c;
        field_combo.hwpe_job_dep.in_d2.stride.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.in_d2.stride.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.in_d2.stride.load_next) begin
                field_storage.hwpe_job_dep.in_d2.stride.value <= field_combo.hwpe_job_dep.in_d2.stride.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.in_d2.stride.value = field_storage.hwpe_job_dep.in_d2.stride.value;
    // Field: datamover_regif.hwpe_job_dep.in_d3.length
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.in_d3.length.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.in_d3 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.in_d3.length.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.in_d3.length.next = next_c;
        field_combo.hwpe_job_dep.in_d3.length.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.in_d3.length.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.in_d3.length.load_next) begin
                field_storage.hwpe_job_dep.in_d3.length.value <= field_combo.hwpe_job_dep.in_d3.length.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.in_d3.length.value = field_storage.hwpe_job_dep.in_d3.length.value;
    // Field: datamover_regif.hwpe_job_dep.in_d3.stride
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.in_d3.stride.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.in_d3 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.in_d3.stride.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.in_d3.stride.next = next_c;
        field_combo.hwpe_job_dep.in_d3.stride.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.in_d3.stride.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.in_d3.stride.load_next) begin
                field_storage.hwpe_job_dep.in_d3.stride.value <= field_combo.hwpe_job_dep.in_d3.stride.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.in_d3.stride.value = field_storage.hwpe_job_dep.in_d3.stride.value;
    // Field: datamover_regif.hwpe_job_dep.out_d0.length
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.out_d0.length.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.out_d0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.out_d0.length.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.out_d0.length.next = next_c;
        field_combo.hwpe_job_dep.out_d0.length.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.out_d0.length.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.out_d0.length.load_next) begin
                field_storage.hwpe_job_dep.out_d0.length.value <= field_combo.hwpe_job_dep.out_d0.length.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.out_d0.length.value = field_storage.hwpe_job_dep.out_d0.length.value;
    // Field: datamover_regif.hwpe_job_dep.out_d0.stride
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.out_d0.stride.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.out_d0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.out_d0.stride.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.out_d0.stride.next = next_c;
        field_combo.hwpe_job_dep.out_d0.stride.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.out_d0.stride.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.out_d0.stride.load_next) begin
                field_storage.hwpe_job_dep.out_d0.stride.value <= field_combo.hwpe_job_dep.out_d0.stride.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.out_d0.stride.value = field_storage.hwpe_job_dep.out_d0.stride.value;
    // Field: datamover_regif.hwpe_job_dep.out_d1.length
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.out_d1.length.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.out_d1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.out_d1.length.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.out_d1.length.next = next_c;
        field_combo.hwpe_job_dep.out_d1.length.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.out_d1.length.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.out_d1.length.load_next) begin
                field_storage.hwpe_job_dep.out_d1.length.value <= field_combo.hwpe_job_dep.out_d1.length.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.out_d1.length.value = field_storage.hwpe_job_dep.out_d1.length.value;
    // Field: datamover_regif.hwpe_job_dep.out_d1.stride
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.out_d1.stride.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.out_d1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.out_d1.stride.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.out_d1.stride.next = next_c;
        field_combo.hwpe_job_dep.out_d1.stride.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.out_d1.stride.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.out_d1.stride.load_next) begin
                field_storage.hwpe_job_dep.out_d1.stride.value <= field_combo.hwpe_job_dep.out_d1.stride.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.out_d1.stride.value = field_storage.hwpe_job_dep.out_d1.stride.value;
    // Field: datamover_regif.hwpe_job_dep.out_d2.length
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.out_d2.length.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.out_d2 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.out_d2.length.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.out_d2.length.next = next_c;
        field_combo.hwpe_job_dep.out_d2.length.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.out_d2.length.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.out_d2.length.load_next) begin
                field_storage.hwpe_job_dep.out_d2.length.value <= field_combo.hwpe_job_dep.out_d2.length.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.out_d2.length.value = field_storage.hwpe_job_dep.out_d2.length.value;
    // Field: datamover_regif.hwpe_job_dep.out_d2.stride
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.out_d2.stride.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.out_d2 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.out_d2.stride.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.out_d2.stride.next = next_c;
        field_combo.hwpe_job_dep.out_d2.stride.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.out_d2.stride.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.out_d2.stride.load_next) begin
                field_storage.hwpe_job_dep.out_d2.stride.value <= field_combo.hwpe_job_dep.out_d2.stride.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.out_d2.stride.value = field_storage.hwpe_job_dep.out_d2.stride.value;
    // Field: datamover_regif.hwpe_job_dep.out_d3.length
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.out_d3.length.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.out_d3 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.out_d3.length.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.out_d3.length.next = next_c;
        field_combo.hwpe_job_dep.out_d3.length.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.out_d3.length.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.out_d3.length.load_next) begin
                field_storage.hwpe_job_dep.out_d3.length.value <= field_combo.hwpe_job_dep.out_d3.length.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.out_d3.length.value = field_storage.hwpe_job_dep.out_d3.length.value;
    // Field: datamover_regif.hwpe_job_dep.out_d3.stride
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.out_d3.stride.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.out_d3 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.out_d3.stride.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.out_d3.stride.next = next_c;
        field_combo.hwpe_job_dep.out_d3.stride.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.out_d3.stride.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.out_d3.stride.load_next) begin
                field_storage.hwpe_job_dep.out_d3.stride.value <= field_combo.hwpe_job_dep.out_d3.stride.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.out_d3.stride.value = field_storage.hwpe_job_dep.out_d3.stride.value;
    // Field: datamover_regif.hwpe_job_dep.in_out_d4_stride.in_stride
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.in_out_d4_stride.in_stride.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.in_out_d4_stride && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.in_out_d4_stride.in_stride.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.in_out_d4_stride.in_stride.next = next_c;
        field_combo.hwpe_job_dep.in_out_d4_stride.in_stride.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.in_out_d4_stride.in_stride.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.in_out_d4_stride.in_stride.load_next) begin
                field_storage.hwpe_job_dep.in_out_d4_stride.in_stride.value <= field_combo.hwpe_job_dep.in_out_d4_stride.in_stride.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.in_out_d4_stride.in_stride.value = field_storage.hwpe_job_dep.in_out_d4_stride.in_stride.value;
    // Field: datamover_regif.hwpe_job_dep.in_out_d4_stride.out_stride
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.in_out_d4_stride.out_stride.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.in_out_d4_stride && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.in_out_d4_stride.out_stride.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.in_out_d4_stride.out_stride.next = next_c;
        field_combo.hwpe_job_dep.in_out_d4_stride.out_stride.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.in_out_d4_stride.out_stride.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.in_out_d4_stride.out_stride.load_next) begin
                field_storage.hwpe_job_dep.in_out_d4_stride.out_stride.value <= field_combo.hwpe_job_dep.in_out_d4_stride.out_stride.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.in_out_d4_stride.out_stride.value = field_storage.hwpe_job_dep.in_out_d4_stride.out_stride.value;
    // Field: datamover_regif.hwpe_job_dep.matrix_dim.tensor_size_m
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.matrix_dim.tensor_size_m.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.matrix_dim && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.matrix_dim.tensor_size_m.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.matrix_dim.tensor_size_m.next = next_c;
        field_combo.hwpe_job_dep.matrix_dim.tensor_size_m.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.matrix_dim.tensor_size_m.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.matrix_dim.tensor_size_m.load_next) begin
                field_storage.hwpe_job_dep.matrix_dim.tensor_size_m.value <= field_combo.hwpe_job_dep.matrix_dim.tensor_size_m.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.matrix_dim.tensor_size_m.value = field_storage.hwpe_job_dep.matrix_dim.tensor_size_m.value;
    // Field: datamover_regif.hwpe_job_dep.matrix_dim.tensor_size_n
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.matrix_dim.tensor_size_n.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.matrix_dim && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.matrix_dim.tensor_size_n.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.matrix_dim.tensor_size_n.next = next_c;
        field_combo.hwpe_job_dep.matrix_dim.tensor_size_n.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.matrix_dim.tensor_size_n.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.matrix_dim.tensor_size_n.load_next) begin
                field_storage.hwpe_job_dep.matrix_dim.tensor_size_n.value <= field_combo.hwpe_job_dep.matrix_dim.tensor_size_n.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.matrix_dim.tensor_size_n.value = field_storage.hwpe_job_dep.matrix_dim.tensor_size_n.value;
    // Field: datamover_regif.hwpe_job_dep.channels.num_channels
    always_comb begin
        automatic logic [10:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.channels.num_channels.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.channels && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.channels.num_channels.value & ~decoded_wr_biten[10:0]) | (decoded_wr_data[10:0] & decoded_wr_biten[10:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.channels.num_channels.next = next_c;
        field_combo.hwpe_job_dep.channels.num_channels.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.channels.num_channels.value <= 11'h0;
        end else begin
            if(field_combo.hwpe_job_dep.channels.num_channels.load_next) begin
                field_storage.hwpe_job_dep.channels.num_channels.value <= field_combo.hwpe_job_dep.channels.num_channels.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.channels.num_channels.value = field_storage.hwpe_job_dep.channels.num_channels.value;
    // Field: datamover_regif.hwpe_job_dep.channels.total_elements
    always_comb begin
        automatic logic [20:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.channels.total_elements.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.channels && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.channels.total_elements.value & ~decoded_wr_biten[31:11]) | (decoded_wr_data[31:11] & decoded_wr_biten[31:11]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.channels.total_elements.next = next_c;
        field_combo.hwpe_job_dep.channels.total_elements.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.channels.total_elements.value <= 21'h0;
        end else begin
            if(field_combo.hwpe_job_dep.channels.total_elements.load_next) begin
                field_storage.hwpe_job_dep.channels.total_elements.value <= field_combo.hwpe_job_dep.channels.total_elements.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.channels.total_elements.value = field_storage.hwpe_job_dep.channels.total_elements.value;
    // Field: datamover_regif.hwpe_job_dep.ctrl_engine.transp_mode
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.ctrl_engine.transp_mode.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.ctrl_engine && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.ctrl_engine.transp_mode.value & ~decoded_wr_biten[2:0]) | (decoded_wr_data[2:0] & decoded_wr_biten[2:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.ctrl_engine.transp_mode.next = next_c;
        field_combo.hwpe_job_dep.ctrl_engine.transp_mode.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.ctrl_engine.transp_mode.value <= 3'h0;
        end else begin
            if(field_combo.hwpe_job_dep.ctrl_engine.transp_mode.load_next) begin
                field_storage.hwpe_job_dep.ctrl_engine.transp_mode.value <= field_combo.hwpe_job_dep.ctrl_engine.transp_mode.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.ctrl_engine.transp_mode.value = field_storage.hwpe_job_dep.ctrl_engine.transp_mode.value;
    // Field: datamover_regif.hwpe_job_dep.ctrl_engine.datamover_mode
    always_comb begin
        automatic logic [4:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.ctrl_engine.datamover_mode.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.ctrl_engine && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.ctrl_engine.datamover_mode.value & ~decoded_wr_biten[7:3]) | (decoded_wr_data[7:3] & decoded_wr_biten[7:3]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.ctrl_engine.datamover_mode.next = next_c;
        field_combo.hwpe_job_dep.ctrl_engine.datamover_mode.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.ctrl_engine.datamover_mode.value <= 5'h0;
        end else begin
            if(field_combo.hwpe_job_dep.ctrl_engine.datamover_mode.load_next) begin
                field_storage.hwpe_job_dep.ctrl_engine.datamover_mode.value <= field_combo.hwpe_job_dep.ctrl_engine.datamover_mode.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.ctrl_engine.datamover_mode.value = field_storage.hwpe_job_dep.ctrl_engine.datamover_mode.value;
    // Field: datamover_regif.hwpe_job_dep.ctrl_engine.read_dim_en
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.ctrl_engine.read_dim_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.ctrl_engine && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.ctrl_engine.read_dim_en.value & ~decoded_wr_biten[11:8]) | (decoded_wr_data[11:8] & decoded_wr_biten[11:8]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.ctrl_engine.read_dim_en.next = next_c;
        field_combo.hwpe_job_dep.ctrl_engine.read_dim_en.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.ctrl_engine.read_dim_en.value <= 4'h0;
        end else begin
            if(field_combo.hwpe_job_dep.ctrl_engine.read_dim_en.load_next) begin
                field_storage.hwpe_job_dep.ctrl_engine.read_dim_en.value <= field_combo.hwpe_job_dep.ctrl_engine.read_dim_en.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.ctrl_engine.read_dim_en.value = field_storage.hwpe_job_dep.ctrl_engine.read_dim_en.value;
    // Field: datamover_regif.hwpe_job_dep.ctrl_engine.write_dim_en
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.ctrl_engine.write_dim_en.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.ctrl_engine && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.ctrl_engine.write_dim_en.value & ~decoded_wr_biten[15:12]) | (decoded_wr_data[15:12] & decoded_wr_biten[15:12]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.ctrl_engine.write_dim_en.next = next_c;
        field_combo.hwpe_job_dep.ctrl_engine.write_dim_en.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.ctrl_engine.write_dim_en.value <= 4'h0;
        end else begin
            if(field_combo.hwpe_job_dep.ctrl_engine.write_dim_en.load_next) begin
                field_storage.hwpe_job_dep.ctrl_engine.write_dim_en.value <= field_combo.hwpe_job_dep.ctrl_engine.write_dim_en.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.ctrl_engine.write_dim_en.value = field_storage.hwpe_job_dep.ctrl_engine.write_dim_en.value;
    // Field: datamover_regif.hwpe_job_dep.ctrl_engine.conv_stride
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.ctrl_engine.conv_stride.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.ctrl_engine && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.ctrl_engine.conv_stride.value & ~decoded_wr_biten[18:16]) | (decoded_wr_data[18:16] & decoded_wr_biten[18:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.ctrl_engine.conv_stride.next = next_c;
        field_combo.hwpe_job_dep.ctrl_engine.conv_stride.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.ctrl_engine.conv_stride.value <= 3'h0;
        end else begin
            if(field_combo.hwpe_job_dep.ctrl_engine.conv_stride.load_next) begin
                field_storage.hwpe_job_dep.ctrl_engine.conv_stride.value <= field_combo.hwpe_job_dep.ctrl_engine.conv_stride.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.ctrl_engine.conv_stride.value = field_storage.hwpe_job_dep.ctrl_engine.conv_stride.value;
    // Field: datamover_regif.hwpe_job_dep.ctrl_engine.reserved
    always_comb begin
        automatic logic [12:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.ctrl_engine.reserved.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.ctrl_engine && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.ctrl_engine.reserved.value & ~decoded_wr_biten[31:19]) | (decoded_wr_data[31:19] & decoded_wr_biten[31:19]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.ctrl_engine.reserved.next = next_c;
        field_combo.hwpe_job_dep.ctrl_engine.reserved.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.ctrl_engine.reserved.value <= 13'h0;
        end else begin
            if(field_combo.hwpe_job_dep.ctrl_engine.reserved.load_next) begin
                field_storage.hwpe_job_dep.ctrl_engine.reserved.value <= field_combo.hwpe_job_dep.ctrl_engine.reserved.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.ctrl_engine.reserved.value = field_storage.hwpe_job_dep.ctrl_engine.reserved.value;
    // Field: datamover_regif.hwpe_job_dep.out_tot_len.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.out_tot_len.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.out_tot_len && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.out_tot_len.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.out_tot_len.value.next = next_c;
        field_combo.hwpe_job_dep.out_tot_len.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.out_tot_len.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.out_tot_len.value.load_next) begin
                field_storage.hwpe_job_dep.out_tot_len.value.value <= field_combo.hwpe_job_dep.out_tot_len.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.out_tot_len.value.value = field_storage.hwpe_job_dep.out_tot_len.value.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [31:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 32'h0) begin
            readback_data_var[31:2] = 30'h0;
        end
        if(rd_mux_addr == 32'h4) begin
            readback_data_var[31:0] = hwif_in.hwpe_ctrl.acquire.acquire.next;
        end
        if(rd_mux_addr == 32'h8) begin
            readback_data_var[0] = field_storage.hwpe_ctrl.autotrigger.autotrigger_n.value;
            readback_data_var[31:1] = 31'h0;
        end
        if(rd_mux_addr == 32'hc) begin
            readback_data_var[31:0] = hwif_in.hwpe_ctrl.status.status0.next;
        end
        if(rd_mux_addr == 32'h10) begin
            readback_data_var[7:0] = hwif_in.hwpe_ctrl.running_job.running_job.next;
            readback_data_var[31:8] = 24'h0;
        end
        if(rd_mux_addr == 32'h14) begin
            readback_data_var[31:2] = 30'h0;
        end
        if(rd_mux_addr == 32'h18) begin
            readback_data_var[31:0] = 32'h0;
        end
        if(rd_mux_addr == 32'h1c) begin
            readback_data_var[31:0] = 32'h0;
        end
        if(rd_mux_addr == 32'h20) begin
            readback_data_var[31:0] = 32'h0;
        end
        if(rd_mux_addr == 32'h40) begin
            readback_data_var[31:0] = field_storage.hwpe_job_dep.in_ptr.value.value;
        end
        if(rd_mux_addr == 32'h44) begin
            readback_data_var[31:0] = field_storage.hwpe_job_dep.out_ptr.value.value;
        end
        if(rd_mux_addr == 32'h48) begin
            readback_data_var[31:0] = field_storage.hwpe_job_dep.tot_len.value.value;
        end
        if(rd_mux_addr == 32'h4c) begin
            readback_data_var[15:0] = field_storage.hwpe_job_dep.in_d0.length.value;
            readback_data_var[31:16] = field_storage.hwpe_job_dep.in_d0.stride.value;
        end
        if(rd_mux_addr == 32'h50) begin
            readback_data_var[15:0] = field_storage.hwpe_job_dep.in_d1.length.value;
            readback_data_var[31:16] = field_storage.hwpe_job_dep.in_d1.stride.value;
        end
        if(rd_mux_addr == 32'h54) begin
            readback_data_var[15:0] = field_storage.hwpe_job_dep.in_d2.length.value;
            readback_data_var[31:16] = field_storage.hwpe_job_dep.in_d2.stride.value;
        end
        if(rd_mux_addr == 32'h58) begin
            readback_data_var[15:0] = field_storage.hwpe_job_dep.in_d3.length.value;
            readback_data_var[31:16] = field_storage.hwpe_job_dep.in_d3.stride.value;
        end
        if(rd_mux_addr == 32'h5c) begin
            readback_data_var[15:0] = field_storage.hwpe_job_dep.out_d0.length.value;
            readback_data_var[31:16] = field_storage.hwpe_job_dep.out_d0.stride.value;
        end
        if(rd_mux_addr == 32'h60) begin
            readback_data_var[15:0] = field_storage.hwpe_job_dep.out_d1.length.value;
            readback_data_var[31:16] = field_storage.hwpe_job_dep.out_d1.stride.value;
        end
        if(rd_mux_addr == 32'h64) begin
            readback_data_var[15:0] = field_storage.hwpe_job_dep.out_d2.length.value;
            readback_data_var[31:16] = field_storage.hwpe_job_dep.out_d2.stride.value;
        end
        if(rd_mux_addr == 32'h68) begin
            readback_data_var[15:0] = field_storage.hwpe_job_dep.out_d3.length.value;
            readback_data_var[31:16] = field_storage.hwpe_job_dep.out_d3.stride.value;
        end
        if(rd_mux_addr == 32'h6c) begin
            readback_data_var[15:0] = field_storage.hwpe_job_dep.in_out_d4_stride.in_stride.value;
            readback_data_var[31:16] = field_storage.hwpe_job_dep.in_out_d4_stride.out_stride.value;
        end
        if(rd_mux_addr == 32'h70) begin
            readback_data_var[15:0] = field_storage.hwpe_job_dep.matrix_dim.tensor_size_m.value;
            readback_data_var[31:16] = field_storage.hwpe_job_dep.matrix_dim.tensor_size_n.value;
        end
        if(rd_mux_addr == 32'h74) begin
            readback_data_var[10:0] = field_storage.hwpe_job_dep.channels.num_channels.value;
            readback_data_var[31:11] = field_storage.hwpe_job_dep.channels.total_elements.value;
        end
        if(rd_mux_addr == 32'h78) begin
            readback_data_var[2:0] = field_storage.hwpe_job_dep.ctrl_engine.transp_mode.value;
            readback_data_var[7:3] = field_storage.hwpe_job_dep.ctrl_engine.datamover_mode.value;
            readback_data_var[11:8] = field_storage.hwpe_job_dep.ctrl_engine.read_dim_en.value;
            readback_data_var[15:12] = field_storage.hwpe_job_dep.ctrl_engine.write_dim_en.value;
            readback_data_var[18:16] = field_storage.hwpe_job_dep.ctrl_engine.conv_stride.value;
            readback_data_var[31:19] = field_storage.hwpe_job_dep.ctrl_engine.reserved.value;
        end
        if(rd_mux_addr == 32'h7c) begin
            readback_data_var[31:0] = field_storage.hwpe_job_dep.out_tot_len.value.value;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
