add wave -noupdate -label testbench_memory /tb_datamover_top_wrap/i_testbench_memory/memory
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/clk_i
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/rst_ni
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/test_mode_i
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/enable_i
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/clear_i
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/randomize_mem
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/stallable_mem
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/tcdm_req
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/tcdm_gnt
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/tcdm_add
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/tcdm_wen
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/tcdm_be
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/tcdm_data
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/tcdm_r_data
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/tcdm_r_valid
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/periph_req
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/periph_gnt
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/periph_add
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/periph_wen
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/periph_be
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/periph_data
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/periph_id
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/periph_r_data
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/periph_r_valid
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/periph_r_id
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/periph_bus
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/read_addr
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/write_addr
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/busy
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/enable_mem
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/status
add wave -noupdate -expand -group tb_datamover_top_wrap /tb_datamover_top_wrap/error_status
